### ISSUE TITLE
getting "image not found" when using with pre-installed tensorflow

### ISSUE THREAD

**Issue by pbgc** [tensorflow/rust#105]
macOS 10.12.6
I have /usr/local/lib/libtensorflow.dylib in place and use it with Haskell TensorFlow bindings without any problem.
(installed by: https://github.com/tensorflow/haskell/blob/master/tools/install_macos_dependencies.sh)

I built an example project without problem:

[labrax:projects/Rust/tftest] pbgc% cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading tensorflow v0.4.0
 Downloading tensorflow-sys v0.8.0
 Downloading tar v0.4.13
 Downloading semver v0.5.1
 Downloading curl v0.4.8
 Downloading pkg-config v0.3.9
 Downloading filetime v0.1.10
 Downloading semver-parser v0.6.2
 Downloading gcc v0.3.53
 Downloading curl-sys v0.3.14
 Downloading socket2 v0.2.2
 Downloading libz-sys v1.0.16
 Downloading xattr v0.1.11
   Compiling num-traits v0.1.40
   Compiling pkg-config v0.3.9
   Compiling libc v0.2.29
   Compiling lazy_static v0.2.8
   Compiling gcc v0.3.53
   Compiling cfg-if v0.1.2
   Compiling regex-syntax v0.3.9
   Compiling utf8-ranges v0.1.3
   Compiling winapi v0.2.8
   Compiling winapi-build v0.1.1
   Compiling kernel32-sys v0.2.2
   Compiling memchr v0.1.11
   Compiling filetime v0.1.10
   Compiling xattr v0.1.11
   Compiling socket2 v0.2.2
   Compiling aho-corasick v0.5.3
   Compiling num-complex v0.1.40
   Compiling tar v0.4.13
   Compiling thread-id v2.0.0
   Compiling thread_local v0.2.7
   Compiling miniz-sys v0.1.9
   Compiling libz-sys v1.0.16
   Compiling curl-sys v0.3.14
   Compiling curl v0.4.8
   Compiling regex v0.1.80
   Compiling flate2 v0.2.19
   Compiling semver-parser v0.6.2
   Compiling semver v0.5.1
   Compiling tensorflow-sys v0.8.0
   Compiling tensorflow v0.4.0
   Compiling tftest v0.1.0 (file:///Users/pbgc/Development/projects/Rust/tftest)
    Finished dev [unoptimized + debuginfo] target(s) in 22.32 secs

when i try to run it I get:

[labrax:projects/Rust/tftest] pbgc% target/debug/tftest
dyld: Library not loaded: bazel-out/local-opt/bin/tensorflow/libtensorflow.so
  Referenced from: /Users/pbgc/Development/projects/Rust/tftest/target/debug/tftest
  Reason: image not found
Abort

**Comment by nbigaouette-eai** [comment]
Some things that came to mind reading this:
1. You seem to run the example directly (`target/debug/tftest`). This will probably fail when using dynamic linking... Could you try with `cargo test` instead?
2. Even though you want to use your pre-installed version of TF, it seems the built binary is dynamically linked to a different library. Maybe the `build.rs` is failing to detect your installed library and is using a downloaded pre-built version.

**Comment by pbgc** [comment]
Maybe I'm not understanding something ... and I apologize ... But I searched and found this file:

tftest/target/debug/build/tensorflow-sys-7b6f973abb590e29/out/libtensorflow.so

I copied to /usr/local/lib/ 

And now it seems that it's working ...

**Comment by nbigaouette-eai** [comment]
The file you found is, I think, the pre-built binary downloaded by the [build.rs](https://github.com/tensorflow/rust/blob/master/tensorflow-sys/build.rs#L70) file and installed in the `target` directory by cargo.

I think cargo should be able to run compiled binaries with the proper path so you should not have to copy the .so file to /usr. If you want to run the binary manually, you will need to set the LD_LIBRARY_PATH to let the binary knows where to find its needed libraries (cargo is doing that for you normally) or copy the file to a known standard path (as you did).

**Comment by pbgc** [comment]
@nbigaouette-eai thank you for you help. As this is working now I will close the issue because I don't know if the content is helpful.
