### ISSUE TITLE
How to deal with negative shape dimensions

### ISSUE THREAD

**Issue by mixam85** [tensorflow/rust#129]
I am trying to use a model generated from keras.
I have converted the `.h5` to `.pb` graph using [this script](https://github.com/amir-abdi/keras_to_tensorflow.) and I am able to load it in rust.
But whenever I try to feed it I get 

`InvalidArgument: You must feed a value for placeholder tensor 'conv2d_13_input' with dtype float and shape [?,8,8,1]`

I try to feed a Tensor created with

`let mut t: Tensor<f32> = Tensor::new(&[1, 8, 8, 1]);`

I guess the problem come from the model definition which starts with

```
node {
  name: "conv2d_13_input"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: -1
        }
        dim {
          size: 8
        }
        dim {
          size: 8
        }
        dim {
          size: 1
        }
      }
    }
  }
}
```
It seams that the C++ `TensorShape` accepts i64 but the constructor of Rust has u64.

Is it a limitation of the Rust binding or is there a workaround ?

Thanks,
Maxime.

**Comment by adamcrume** [comment]
It looks like it's complaining that you're not feeding any value for the placeholder at all.  Make sure you're feeding the tensor into the placeholder like so:

    let t_op: Operation = ...;
    let mut step = StepWithGraph::new();
    step.add_input(&t_op, 0, &t); // this line is probably missing
    session.run(&mut step)?;

If you don't already have `t_op`, you can grab it by doing:

    let t_op = graph.operation_by_name_required("conv2d_13_input")?;

The i64/u64 thing is a bit messy, but in the places where the underlying TensorFlow C API would allow -1, we use `Option<u64>`, and the -1 is `None`.

I hope this helps.  Let me know if this fixes it, and if not, please post a minimal, self-contained snippet that shows the problem.

**Comment by mixam85** [comment]
I thinks I found what went wrong with the help of your comment:

> It looks like it's complaining that you're not feeding any value for the placeholder at all.

Here is my erroneous code:

```
   /* Load model */
    let mut graph = Graph::new();
    let import_options = ImportGraphDefOptions::new();
    graph.import_graph_def(&model_bytes, &import_options)?;


    /* Create session */
    let session_options = SessionOptions::new();
    let mut session = Session::new(&session_options, &graph)?;

    /* Extract input/output layer operations */
    let input_layer = graph.operation_by_name_required("conv2d_13_input")?;
    let output_layer = graph.operation_by_name_required("output_node0")?;

    /* Pepare run */
    let mut run_steps = StepWithGraph::new();
    run_steps.add_input(&input_layer, 0, &input_tensor);
    run_steps.add_target(&output_layer);

    /* Run model */
    session.run(&mut run_steps)?;

    /* Prepare output data */
    let mut output_step = StepWithGraph::new();
    let output_ref = output_step.request_output(&output_layer, 0);

    /* Extract output */
    session.run(&mut output_step)?;
    let output: Tensor<f64> = output_step.take_output(output_ref)?;
```

I had two separated run, one for feeding, and the other one for getting the output like in this [example](https://github.com/tensorflow/rust/blob/master/examples/regression_savedmodel.rs).

By doing extraction in 1 run it worked ok

```
    /* Load model */
    let mut graph = Graph::new();
    let import_options = ImportGraphDefOptions::new();
    graph.import_graph_def(&model_bytes, &import_options)?;


    /* Create session */
    let session_options = SessionOptions::new();
    let mut session = Session::new(&session_options, &graph)?;

    /* Extract input/output layer operations */
    let input_layer = graph.operation_by_name_required("conv2d_13_input")?;
    let output_layer = graph.operation_by_name_required("output_node0")?;

    /* Pepare run */
    let mut run_steps = StepWithGraph::new();
    run_steps.add_input(&input_layer, 0, &input_tensor);
    run_steps.add_target(&output_layer);
    let output_ref = run_steps.request_output(&output_layer, 0);

    /* Run model */
    session.run(&mut run_steps)?;

    /* Extract output */
    let output: Tensor<f32> = run_steps.take_output(output_ref)?;
```

Thanks a lot.
