### ISSUE TITLE
Bump crates.io version

### ISSUE THREAD

**Issue by iduartgomez** [tensorflow/rust#130]
There have been substantial changes/additions in the last months, probably a good idea to bump the crates.io version for libraries which have a dependency, even if a minor version update (0.6.1).

Unless there are any lingering pending changes off course.

**Comment by adamcrume** [comment]
What a coincidence; I was planning on pushing a release this weekend. :)

**Comment by adamcrume** [comment]
I pushed version 0.7.0.
