### ISSUE TITLE
[Question] How can I define concrete types of TensorType?

### ISSUE THREAD

**Issue by y-ich** [tensorflow/rust#133]
Hi.

I am not quite sure that this place is suitable for questions. Let me know if wrong.

I have a Graph that outputs an array of f32. and I want to make a function that outputs the output of the Graph.
So you need to specify the type of output. I guess that It should be an Tensor<T>, but I have no idea about T.
I tried [f32; SOME_SIZE], but the compiler terminates with an error "the trait `tensorflow::TensorType` is not implemented for `[f32; SOME_SIZE]`".

How can I define concrete types of TensorType?

**Comment by Enet4** [comment]
The `TensorType` trait describes a tensor's single element type. The shape of the tensor is defined separately. In this case, I believe that you would want a `Tensor<f32>` as the output of your graph, which in turn could be 1-ranked with the shape `[SOME_SIZE]`. I can only be sure with a concrete minimal example.

**Comment by y-ich** [comment]
Thank you, @Enet4 san!
Now I understood my misunderstanding.
I was confused by seeing several errors.
