### ISSUE TITLE
How to link statically?

### ISSUE THREAD

**Issue by Storyyeller** [tensorflow/rust#156]
How can I force tensorflow to be linked statically? If I just include `tensorflow` in my `cargo.toml` and run `cargo build` like normal, it builds without errors, but the result is dynamically linked and breaks if I move the executable anywhere else.

**Comment by adamcrume** [comment]
I wouldn't recommend statically linking TensorFlow if you don't absolutely need to.  For one, the libraries are around 68 MB.  We also don't currently support it.  The easiest solution is to just install TensorFlow's shared libraries (libtensorflow.so and libtensorflow_framework.so) in the usual place, e.g. /usr/lib.  You can also run your binary with the path to the shared libraries added to the LD_LIBRARY_PATH environment variable.
