### ISSUE TITLE
Wrap TF_GetOpList

### ISSUE THREAD

**Issue by adamcrume** [tensorflow/rust#166]
We have a TODO to wrap TF_GetOpList: https://github.com/tensorflow/rust/blob/a5409d183b2a7301ca946a5d2d13d34e471244ef/src/lib.rs#L1240

Doing this properly requires figuring out proto support, first.

**Comment by kykosic** [comment]
I'd like to take this issue if available. I've already started working on it, but I'm not 100% clear on what to do once I have an `OpList` proto. Are we just storing it as a member of the `Library` struct, matching the pattern in [the C library](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/load_library.cc)?

**Comment by adamcrume** [comment]
Yeah, storing it as a member of the `Library` struct should work.  I'm currently trying to keep our choice of proto library as an implementation detail, so the types used in the public API need to be hand-written protos.

**Comment by allentv** [comment]
@adamcrume Seems like this issue is no longer open with the recent PR merge?

I was searching for `Good First Issue` and only this one came up :-(

**Comment by adamcrume** [comment]
Yep, this was fixed by https://github.com/tensorflow/rust/pull/263, and the issue didn't get closed somehow.  Sorry about that.  I'll go ahead and close it.  I filed some new issues from TODOs in the code and labeled them with `good first issue`.  #289 is probably the easiest, followed by #288.
