### ISSUE TITLE
Remove Python dependencies for speed? 

### ISSUE THREAD

**Issue by rsimmonsjr** [tensorflow/rust#190]
For speed purposes is it possible to replace the python dependencies with something more RUST oriented? I understand the python libs have been around a while but there are problems when it comes to calculation speed.

**Comment by Enet4** [comment]
Can you better explain your concern? The Rust bindings do not depend on Python to function, they are just used in the project for testing purposes. Moreover, considering that TensorFlow has a native, optimized implementation in C++ underneath for the actual mathematical operations, the performance benefit of defining the computational graph in Rust would be negligible.

**Comment by rsimmonsjr** [comment]
I was under the impression that TensorFlow was using Python for execution code. If it is only used for testing, that is great. I just noticed the dependencies on numpy and that is a python lib. So what  aspects of the numerical calculations use python if any? I am interested in integrating TensorFlow for our data scientists but I am not one myself.

**Comment by Enet4** [comment]
> I just noticed the dependencies on numpy and that is a python lib.

That only applies to the Python API for TensorFlow, which provides several high-level abstractions on top of the framework for easy experimentation. Numpy, in that context, is mostly used for feeding data and returning outputs from session runs. The actual computations are carried out by native primitives  on CPU or GPU.

> I am interested in integrating TensorFlow for our data scientists but I am not one myself.

I'm afraid that this would be out of the scope of the Rust bindings. You may wish to learn more about TensorFlow at the [official website](https://www.tensorflow.org/), so as to understand how it would be integrated into your team's workflows. At some point, one could use the Rust bindings to deploy trained models to production.

**Comment by rsimmonsjr** [comment]
If its not used in live production then I wouldn't care. If, as you say, its only used for python talking to tensorflow then I have no issues as I would talk to it with rust.

**Comment by rsimmonsjr** [comment]
If that is the case above, I am happy to have this issue closed.
