### ISSUE TITLE
tensorflow_sys::TF_Session cannot be sent between threads safely

### ISSUE THREAD

**Issue by cetra3** [tensorflow/rust#192]
I'm not sure if this is actually the case, but according to the standard [Tensorflow documentation](https://www.tensorflow.org/api_guides/python/threading_and_queues#Manual_Thread_Management) the python API says that sessions are thread safe.

I get the following error when I try and share a session in a Mutex:

```
`*mut tensorflow_sys::TF_Session` cannot be sent between threads safely
   |
   = help: within `fnet::Fnet`, the trait `std::marker::Send` is not implemented for `*mut tensorflow_sys::TF_Session`
   = note: required because it appears within the type `tensorflow::session::Session`
   = note: required because it appears within the type `struct::MyStruct`
   = note: required because of the requirements on the impl of `std::marker::Sync` for `std::sync::Mutex<struct::MyStruct>`
   = note: required by `lazy_static::lazy::Lazy`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

I am assuming this is just because rust is conservative when dealing with raw pointers?

**Comment by adamcrume** [comment]
I can't change the behavior of `*mut tensorflow_sys::TF_Session` because that is built into Rust.  I can implement `Send` and `Sync` for `tensorflow::Session`, which does seem to make sense.  We probably need to find other types that can be marked as `Send` and `Sync`, since many of the types contain raw pointers and won't automatically implement those traits.

It's not immediately clear whether the thread-safety of Python Session objects necessarily translates to thread-safety of `*mut tensorflow_sys::TF_Session`, so wrapping `tensorflow::Session` in a mutex seems appropriate for now.  Of course, that doesn't help concurrency.

Out of curiosity, why do you want to share a session between threads?

**Comment by adamcrume** [comment]
@jhseu Can `TF_Session`s be shared across threads without additional synchronization?  If I call `TF_SessionRun` concurrently in multiple threads with the same session, is it guaranteed to do something reasonable and safe?  I would expect complications when doing things like updating variables.

**Comment by cetra3** [comment]
Yeah, to work around it, I basically added an unsafe impl to a struct for `Send`.  Then I access behind a Mutex.  I haven't seen any weird race conditions or segfaults in using this method.

My understanding is that even if it's marked `Sync`, because [TF_Session::run()](https://github.com/tensorflow/rust/blob/master/src/session.rs#L146) takes `self` as `&mut`, it'd still need to be behind a mutex or similar, so that would have to change the signature of the method from:

```
pub fn run(&mut self, step: &mut SessionRunArgs) -> Result<()>
```

To

```
pub fn run(&self, step: &mut SessionRunArgs) -> Result<()>
```

I don't know whether the `inner` session changes between runs, so this probably might not be safe.  It'd be great if it could be changed to not require `mut` when running.

As to my motivation:  The neural nets I've been using (facenet & mtcnn) use around ~2gb RAM per session and I don't really see a justifiable performance increase making a session per thread.  

Last check on a MacBook Pro was probably about 200ms shaved off, but for 4x the RAM.  I'm assuming this is because internally tensorflow will use all physical CPU cores to run graphs, so having multiple sessions isn't going to speed up too much, although it does eliminate lock contention.

**Comment by jhseu** [comment]
@adamcrume it's safe from a Session standpoint, but the Graph itself is an arbitrary computation and may be subject to race conditions regarding variables as you mentioned. It's common to use a single Session in multiple threads for inference because the variables aren't mutated in that setting.
