### ISSUE TITLE
Provide a `Half: TensorType`

### ISSUE THREAD

**Issue by nagisa** [tensorflow/rust#196]
Currently it is impossible to feed or fetch from the graphs that work with half precision floats.

**Comment by ehsanmok** [comment]
@adamcrume I have a PR ready for it, but before sending it, it seems there's no `rustfmt.toml` so should I include the changes incurred from that as well?

I think better first to have the `rustfmt.toml` to regulate the formatting across and the [previous PR](https://github.com/tensorflow/rust/pull/51) in this regard is not enough!

**Comment by adamcrume** [comment]
You're welcome to format modified lines, but please don't format everything.  We need to set up a test in Travis to reject improperly formatted pull requests and reformat everything one last time in a single pull request with nothing else in it.

**Comment by ehsanmok** [comment]
@adamcrume This can be closed now.
