### ISSUE TITLE
Segmentation fault when accessing output consumers

### ISSUE THREAD

**Issue by jocaml** [tensorflow/rust#208]
Using version 0.13.0, when I try to call any method on members of the `op.output_consumers(i)`vector, I get a segmentation fault:
```rust
fn f(graph: &Graph) {
    let placeholders = graph
        .operation_iter()
        .filter(|op| op.op_type() == Ok("Placeholder".into()));

    for op in placeholders {
        for i in 0..op.num_outputs() {
            for (consumer_op, input_index) in op.output_consumers(i) {
                consumer_op.input(input_index); // Segmentation fault (core dumped)
            }
        }
    }
}
```
Here is a [valgrind log](https://github.com/tensorflow/rust/files/3235555/valgrind.log). Not sure if this should be submitted to the tensorflow repo.
Here is the cargo project: [tf.zip](https://github.com/tensorflow/rust/files/3235562/tf.zip)

Edit: I've uploaded a new valgrind log, the last one had some garbage from other dependencies (though not sure how they ended up in there hm).

**Comment by jocaml** [comment]
I tried it with all versions from 0.9.0 (tensorflow 1.7.0) and it's the same. On one run I managed to get
```rust
[src/tf.rs:104] consumer_op.input(input_index) = (
    Operation {
        inner: 0x0000000000000000,
        gimpl: GraphImpl {
            inner: 0x000056278c30bb50,
            owned: true,
        },
    },
    18446744073709551615,
)
``` 
Is prebuilt downloaded TensorFlow compiled with jemalloc?

**Comment by adamcrume** [comment]
I've tracked it down to a bug in the Rust bindings.  I'll submit a fix.

**Comment by adamcrume** [comment]
By the way, the prebuilt TensorFlow is compiled with jemalloc.  I have to disable it and compile TensorFlow from scratch (which takes quite a while) to check for memory leaks with valgrind.
