### ISSUE TITLE
Load MetaGraphDef

### ISSUE THREAD

**Issue by r-wheeler** [tensorflow/rust#211]
Is it possible to load the `meta_graph_def: Vec<u8>` object similar to the python API? Ideally looking to be able to get the `tag_set`, `signature_defs` input / output nodes from a saved model similar to the `saved_model_cli` tool 

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/saved_model_utils.py#L90 

`saved_model_cli show --dir \
/tmp/saved_model_dir --tag_set serve --signature_def serving_default`

This would be useful to not need to apriori identify the input / output nodes in order to use `graph.operation_by_name_required` but instead derive them entirely in rust ?

**Comment by Enet4** [comment]
You can couple the library with a protocol buffers parser (e.g. `protobuf`) and parse those bytes as a meta graph definition, according to the official definition of [`MetaGraphDef`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/protobuf/meta_graph.proto).

**Comment by johnwaltonvi** [comment]
just wanted to say cool project hope it grows and evolves nicely!

**Comment by xd009642** [comment]
I think this issue could be closed, there's now a public interface for the MetaGraphDef in master it's just yet-to-be-released

**Comment by adamcrume** [comment]
This is available through `SavedModelBundle::meta_graph_def()` in the latest release (0.16.1).
