### ISSUE TITLE
Add automatic differentiation

### ISSUE THREAD

**Issue by adamcrume** [tensorflow/rust#22]
Many optimization algorithms require derivatives, and support for automatic differentiation would make using them much simpler.

**Comment by Kizilaslan** [comment]
Sahinbeybelediye27@hotmail.com

**Comment by iduartgomez** [comment]
We may be able to get autodiff now: https://github.com/tensorflow/tensorflow/issues/6268 may have been blocking, but seems that gradient support is being added to C++ and may make it "soon" to the C API (ie. check https://github.com/tensorflow/tensorflow/issues/9150#issuecomment-299056067 and below)

**Comment by adamcrume** [comment]
Support for gradients was added in 7542bf422.
