### ISSUE TITLE
Cargo problems when building

### ISSUE THREAD

**Issue by maherkhalil07** [tensorflow/rust#228]
cargo did not build the crate and send the below mentioned messages
error: failed to run custom build command for `tensorflow-sys v0.17.0`

Caused by:
  process didn't exit successfully: `/media/maher/extra/rust/rust_test_code/tensorflow/target/debug/build/tensorflow-sys-417a51948725d608/build-script-build` (exit code: 101)
--- stdout
libtensorflow-sys/build.rs:119: binary_url = "https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-1.13.1.tar.gz"
libtensorflow-sys/build.rs:123: base_name = "libtensorflow-cpu-linux-x86_64-1.13.1"
libtensorflow-sys/build.rs:132: file_name = "/home/maher/.cargo/registry/src/github.com-1ecc6299db9ec823/tensorflow-sys-0.17.0/target/libtensorflow-cpu-linux-x86_64-1.13.1.tar.gz"

--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidInput, error: TarError { desc: "failed to unpack `/home/maher/.cargo/registry/src/github.com-1ecc6299db9ec823/tensorflow-sys-0.17.0/target/libtensorflow-cpu-linux-x86_64-1.13.1/lib/libtensorflow_framework.so`", io: Custom { kind: InvalidInput, error: TarError { desc: "failed to unpack `./lib/libtensorflow_framework.so` into `/home/maher/.cargo/registry/src/github.com-1ecc6299db9ec823/tensorflow-sys-0.17.0/target/libtensorflow-cpu-linux-x86_64-1.13.1/lib/libtensorflow_framework.so`", io: Custom { kind: InvalidInput, error: "corrupt deflate stream" } } } } }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by adamcrume** [comment]
Have you tried running `cargo clean` and then rebuilding?  It looks like the TensorFlow download was corrupted.

**Comment by allentv** [comment]
@maherkhalil07 Not sure if you are still seeing this problem. I just ran `cargo build -j 1` on my Mac (v11.1) and everything seems to work fine.

```bash
 ~/workspace/RustWorkspace/test_tensorflow   master  cargo build -j 1          
    Updating crates.io index
  Downloaded podio v0.1.7
  Downloaded half v1.6.0
  Downloaded tar v0.4.30
  Downloaded socket2 v0.3.19
  Downloaded zip v0.5.6
  Downloaded crc v1.8.1
  Downloaded filetime v0.2.13
  Downloaded curl v0.4.34
  Downloaded build_const v0.2.1
  Downloaded xattr v0.2.2
  Downloaded bzip2 v0.3.3
  Downloaded protobuf v2.17.0
  Downloaded libc v0.2.81
  Downloaded num-complex v0.2.4
  Downloaded bzip2-sys v0.1.9+1.0.8
  Downloaded curl-sys v0.4.39+curl-7.74.0
  Downloaded tensorflow-internal-macros v0.0.1
  Downloaded tensorflow-sys v0.19.1
  Downloaded tensorflow v0.16.1
  Downloaded 19 crates (4.8 MB) in 2.30s (largest was `curl-sys` at 2.9 MB)
   Compiling libc v0.2.81
   Compiling cc v1.0.66
   Compiling pkg-config v0.3.19
   Compiling autocfg v1.0.1
   Compiling cfg-if v1.0.0
   Compiling crc32fast v1.2.1
   Compiling adler v0.2.3
   Compiling proc-macro2 v0.4.30
   Compiling curl v0.4.34
   Compiling unicode-xid v0.1.0
   Compiling podio v0.1.7
   Compiling semver-parser v0.7.0
   Compiling build_const v0.2.1
   Compiling syn v0.15.44
   Compiling protobuf v2.17.0
   Compiling byteorder v1.3.4
   Compiling half v1.6.0
   Compiling libz-sys v1.1.2
   Compiling bzip2-sys v0.1.9+1.0.8
   Compiling curl-sys v0.4.39+curl-7.74.0
   Compiling miniz_oxide v0.4.3
   Compiling num-traits v0.2.14
   Compiling num-complex v0.2.4
   Compiling semver v0.9.0
   Compiling crc v1.8.1
   Compiling filetime v0.2.13
   Compiling xattr v0.2.2
   Compiling socket2 v0.3.19
   Compiling time v0.1.44
   Compiling quote v0.6.13
   Compiling tar v0.4.30
   Compiling bzip2 v0.3.3
   Compiling flate2 v1.0.19
   Compiling zip v0.5.6
   Compiling tensorflow-internal-macros v0.0.1
   Compiling tensorflow-sys v0.19.1
   Compiling tensorflow v0.16.1
   Compiling test_tensorflow v0.1.0 (/Users/allenthomasvarghese/workspace/RustWorkspace/test_tensorflow)
   Finished dev [unoptimized + debuginfo] target(s) in 4m 23s
```

**Comment by adamcrume** [comment]
This was probably transient, so I'll go ahead and close it.  Feel free to reopen if it happens again with the same error, though ("corrupt deflate stream").
