### ISSUE TITLE
Tensorflow 2.0 saved model

### ISSUE THREAD

**Issue by AndreaCatania** [tensorflow/rust#229]
I'm defining a model using Tensorflow 2.0, so I've:

```python
# Define the SummatorModule that sum the submitted value with the previosly
# submitted one
class SummatorModule(tf.Module):
    def __init__(self):
        super(SummatorModule, self).__init__()
        self.a = tf.Variable(tf.zeros(shape=(1, 1)), name='a')

    @tf.function
    def __call__(self, x):
        self.a.assign(self.a + x)
        return self.a
```

And in python I can get a result by simply calling: 
```python
print(summator(number))
print(summator(number))
print(summator(number))
```
```console
tf.Tensor([[1.]], shape=(1, 1), dtype=float32)
tf.Tensor([[2.]], shape=(1, 1), dtype=float32)
tf.Tensor([[3.]], shape=(1, 1), dtype=float32)
```
I'm storing this model using `tf.saved_model.save(summator, sm_dir)`, and now I would like to load and use it in Rust.

The problem is that the variable `X` in not anymore a placeholder rather it's a unamed variable, so how am I supposed to take this operation and feed a new value?

**Comment by adamcrume** [comment]
TensorFlow 2 is unsupported in Rust at the moment.  (The C API for TensorFlow 2 has not been released, yet.)  I'm still learning about TensorFlow 2, but I suspect you need to parse the MetaGraphDef proto to find the right signature and get the name of the input and output tensors from that.  You might also need to change your `@tf.function` decoration to something like `@tf.function(input_signature=[tf.TensorSpec(shape=None, dtype=tf.float32)])`.

When I tried this, the input tensor was `serving_default_x`, and the output tensor was `StatefulPartitionedCall`:

```
$ saved_model_cli show --dir=summator-saved-model --tag_set=serve --signature=serving_default
The given SavedModel SignatureDef contains the following input(s):
  inputs['x'] tensor_info:
      dtype: DT_FLOAT
      shape: unknown_rank
      name: serving_default_x:0
The given SavedModel SignatureDef contains the following output(s):
  outputs['output_0'] tensor_info:
      dtype: DT_FLOAT
      shape: (1, 1)
      name: StatefulPartitionedCall:0
Method name is: tensorflow/serving/predict
```

You can do this in Rust by loading the graph with `SavedModelBundle::load` and parsing `SavedModelBundle::meta_graph_def` with something like https://crates.io/crates/protobuf.

I'm afraid we don't support this out-of-the-box at the moment.

**Comment by AndreaCatania** [comment]
Ok this cliryfied everything, thanks. Looking forward for the release of Tensorflow 2.0 C APIs.
