### ISSUE TITLE
Float 16 to float 32 looks incorrect

### ISSUE THREAD

**Issue by daniel-emotech** [tensorflow/rust#233]
This doesn't look correct. The exponent + sign for 16 bit floats is 6 bits and for 32 bit floats is 9 bits. If you simply shift the bits then parts of the mantissa for the half precision will be in the exponent for full precision (and the inverse). 

```Rust
impl Into<f32> for BFloat16 {
    fn into(self) -> f32 {
        unsafe {
            // Assumes that the architecture uses IEEE-754 natively for floats
            // and twos-complement for integers.
            mem::transmute::<u32, f32>((self.0 as u32) << 16)
        }
    }
}

impl From<f32> for BFloat16 {
    fn from(value: f32) -> Self {
        unsafe {
            // Assumes that the architecture uses IEEE-754 natively for floats
            // and twos-complement for integers.
            BFloat16((mem::transmute::<f32, u32>(value) >> 16) as u16)
        }
    }
}
```

**Comment by adamcrume** [comment]
BFloat16 is not an IEEE-754 16-bit float.  See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/bfloat16.h.

**Comment by xd009642** [comment]
Ah fair enough, I guess that makes sense from a performance perspective. Might be worth adding a note in a doc comment? Though I'm not sure how many other people will notice/care

**Comment by xd009642** [comment]
Also I'm daniel-emotech as well this is just my personal account not my work account :smile:

**Comment by adamcrume** [comment]
I added a couple of comments.
