### ISSUE TITLE
Update prebuilt library

### ISSUE THREAD

**Issue by xd009642** [tensorflow/rust#238]
Is there any issues with updating the prebuilt library to tensorflow 1.14 or 1.15 in terms of compatibility?

**Comment by adamcrume** [comment]
I assume you're asking about e.g. using version 0.14.0 of the `tensorflow` crate (which requires TensorFlow 1.13.1) with libraries from a higher version of TensorFlow (e.g. 1.14).  That *should* work.  The TensorFlow C API has made backwards incompatible changes occasionally, but it's been pretty stable for a while.

By the way, there is a mailing list, which is a good forum for questions: https://groups.google.com/a/tensorflow.org/forum/#!forum/rust

**Comment by xd009642** [comment]
Yeah so my question was more in the line of are there any backwards incompatible changes that stop it being updated to a newer version? If so it would be nice to see a new release with a newer pre 2.0 version at some pont

**Comment by adamcrume** [comment]
I haven't tested the `tensorflow` crate version 0.14.0 with TensorFlow 1.14, so I can't guarantee whether it works or not.  I do plan on releasing at least one more version before switching to TensorFlow 2.

**Comment by danieldk** [comment]
We are using the `tensorflow` crate with Tensorflow 1.15.0 and have it used with 1.14.1 before, without any problems.
