### ISSUE TITLE
Graph extension on `SessionWithGraph`?

### ISSUE THREAD

**Issue by daschl** [tensorflow/rust#24]
Hi,

when switching over from the deprecated `Session`,  one thing I'm missing is the `extend_graph` property. I have the feeling this should now be possible on the `Graph` struct/impl itself, but I checked the public API as well as the FFI one and couldn't find out how to do it.

Is there something I've missed or is it just not implemented yet?

Thanks!

**Comment by adamcrume** [comment]
You're not missing anything.  We're currently on TensorFlow v0.10.0, which doesn't support this.  At v0.11.0, though, there's the `TF_GraphImportGraphDef` function.

**Comment by daschl** [comment]
Okay thanks, then I'll stick with the deprecated `Session` for now.

**Comment by adamcrume** [comment]
We have `Graph::import_graph_def` now.
