### ISSUE TITLE
C API stability statement in docs

### ISSUE THREAD

**Issue by joelberkeley-pio** [tensorflow/rust#243]
The README states

> Notice: This project is still under active development and not guaranteed to have a stable API. This is especially true because the underlying TensorFlow C API has not yet been stabilized as well.

but the [tensorflow version compatibility page](https://www.tensorflow.org/guide/versions) states that the C API is part of the public API, and is therefore

> backwards compatible across minor and patch versions

Is the README correct?

**Comment by Enet4** [comment]
It was true that the C API was not within the project's stability guarantees a few years ago. I suppose this has changed with time.

**Comment by joelberkeley-pio** [comment]
I'd be really interested to know what the stability guarantees of the rust API are given this change of circumstances

**Comment by adamcrume** [comment]
The README is out of date about the C bindings.  I'll fix that.

The Rust bindings have been pretty stable in practice, but there are still major additions to make (e.g. stabilizing building models in Rust), and I don't want to announce the project as stable until at least that is done.
