### ISSUE TITLE
Tensorflow 2.0 support

### ISSUE THREAD

**Issue by r-wheeler** [tensorflow/rust#252]
Thanks for the excellent bindings, we have had great success using them. Do you know when  tensorflow 2 saved models will be supported? 

I have inquired in other channels about the stability of the tensorflow 2.0 C API but not gotten a response.

**Comment by Arnold1** [comment]
hi @r-wheeler is  tensorflow 2.0 C API  already released?

**Comment by claytoncasey01** [comment]
> hi @r-wheeler is tensorflow 2.0 C API already released?

The C++ API for tensorflow core is currently at 2.2.0.

**Comment by kykosic** [comment]
The C++ core is different than the C lib. Per [the docs](https://www.tensorflow.org/install/lang_c), libtensorflow C 2.0+ isn't expected until core 2.3. 

In the meantime, some beta work could be done using [the nightly builds](https://storage.googleapis.com/libtensorflow-nightly), which currently are on 2.2.0. I've been able to compile and run tests against these with no issues.

**Comment by r-wheeler** [comment]
Thanks @kykosic The last time I had looked at the  C lib it had not yet specified a release. I believe I saw an announcement that 2.3 would bet cut on 6/22. 

I would love to be able to jump in and contribute to this project. Any good starting points to help with a 2.x version of these bindings?

**Comment by Arnold1** [comment]
is there a big change planned for 2.3 - or why they release a new c lib with 2.3?

**Comment by kykosic** [comment]
I don't see anything big on the project page https://github.com/orgs/tensorflow/projects/9 (or anything mentioning the C API). It seems that the C API was just not prioritized with the TF2.0 release, but the few comments from internal devs have repeated that they plan to have it back by with the 2.3 release. According to the mailing list, the branch should have been cut yesterday https://groups.google.com/a/tensorflow.org/forum/#!topic/developers/u1eTZtaAxwo

**Comment by kykosic** [comment]
TF 2.3 was released yesterday, and it looks like the 2.3 C lib has been published along with it [https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-2.3.0.tar.gz](https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-2.3.0.tar.gz)

**Comment by DouglasLivingstone** [comment]
From the history of [c_api.h](https://github.com/tensorflow/tensorflow/commits/master/tensorflow/c/c_api.h) it looks like there have been some breaking changes, [this commit](https://github.com/tensorflow/tensorflow/commit/24f835217fd27f21141ff0254a2b93ea3cfd7b6c#diff-3210f0e7c16d97de9fc4419195103c29) removed `TF_StringEncode` and `TF_StringDecode`, so [bindgen.rs](https://github.com/tensorflow/rust/blob/c129a9eb3cd648022cbfca7b0b290f8bae032a63/tensorflow-sys/src/bindgen.rs#L351) would need to be updated.

**Comment by kahlil29** [comment]
Now that TF2.3 is released with the C Lib, is there a lot of more work to be done before we can achieve Tensorflow 2 support?

**Comment by adamcrume** [comment]
I'm working on the upgrade, but I'm running into segfaults, so it's probably not going to be quick and easy.

**Comment by kahlil29** [comment]
Thanks for the update!
Let me know if I can help in any way :)

**Comment by tallamjr** [comment]
Me too, I would love to help where possible, but would need some guidance on where to start. 

The [docs for extending to other language bindings](https://github.com/tensorflow/docs/blob/master/site/en/r1/guide/extend/bindings.md) seems to be out-of-date? Or at least it is filed away under a directory specific for TF1 guides according to this [commit](https://github.com/tensorflow/docs/commit/82a6055d1ed14bbdd156dea9ebc1547e2b31249d)

Does anyone know how one could get going on this, or perhaps where in general one could learn about extending the bindings to rust? 

Disclaimer, I am very new to rust, but this project really excites me and happy to throw myself in the deep end to help!

> Thanks @kykosic The last time I had looked at the C lib it had not yet specified a release. I believe I saw an announcement that 2.3 would bet cut on 6/22.
> 
> I would love to be able to jump in and contribute to this project. Any good starting points to help with a 2.x version of these bindings?

**Comment by adamcrume** [comment]
I have a PR open to upgrade to TensorFlow 2.  I could use help from someone with a Mac (regenerating test_resources/library/macos/test_op.so) as well as help from someone on Windows, verifying that it works as expected.  In general, lots of testing at HEAD before releasing the next version of the crate would help gain confidence, since this is a major bump.

I'm not sure why I was getting segfaults earlier; this looks like a small change API-wise; the issues were more with packaging and a newer version of bindgen.

It looks like the breaking string changes are coming in 2.4.0.

**Comment by kahlil29** [comment]
Thanks for the effort on this @adamcrume 🥇 🎉 
I can help to test this on a Mac. Since the PR is merged, I'm guessing that I can now test using the `master` branch?

**Comment by adamcrume** [comment]
Yes, it's ready for testing on the `master` branch.
