### ISSUE TITLE
used tensorflow version

### ISSUE THREAD

**Issue by amircodota** [tensorflow/rust#253]
Hi,

I'm fairly new to rust and tensorflow, so I might be missing something obvious :-(

I'm using the tensorflow crate version 0.15.0. My understanding is that by default it should use tesnsorflow version 1.15.0. However, no matter what I try, it keeps using tensorflow 1.13.1.

I thought my machine might be "dirty", so I tried it on a clean VM in the cloud, on a brand new rust project, that simply prints out `tensorflow::version()` but it still uses tensorflow 1.13.1.

Any idea?

Amir

**Comment by adamcrume** [comment]
The TensorFlow version is not simply 1 + the crate version.  Version 0.15.0 of the crate does use TensorFlow  1.13.1.

By the way, if you have a question, the [mailing list](https://groups.google.com/a/tensorflow.org/forum/#!forum/rust) is a good place to ask.

**Comment by amircodota** [comment]
Oh, sorry.

Was looking at [this line](https://github.com/tensorflow/rust/blob/3fd2c454d0c70d783f1e1879b2813f232079ed64/tensorflow-sys/build.rs#L32), but I guess it is not released yet.
