### ISSUE TITLE
Tensor interop with `ndarray`

### ISSUE THREAD

**Issue by kykosic** [tensorflow/rust#260]
I've found working with raw Tensor objects in rust to be somewhat tedious. I think it would be useful to add methods to cast between `Tensor` structs and [ndarray objects](https://docs.rs/ndarray/0.13.1/ndarray/) similar to how core TensorFlow python has builtin methods for casting with numpy. 

The Tensor object could impl directly a `Tensor::from_ndarray` method and `Tensor.to_ndarray` method to support this. Alternatively this could be made generic using `std::convert::TryFrom` and `std::convert::TryInto`, and implementations can be provided for correct ndarray objects.

Any thoughts, comments, or concerns about this idea?

**Comment by r-wheeler** [comment]
@kykosic Dont know if you have seen this but the folks at snipsco do this. They have an internal representation of a [tensor](https://github.com/snipsco/tract/blob/master/core/src/tensor.rs) and cast some tensorflow proto into this https://github.com/snipsco/tract/blob/master/tensorflow/src/tensor.rs

I did something similar for an internal project using these bindings and ndarray

**Comment by kykosic** [comment]
Nice one, I hand't seen that. I haven't heard of tract, but this is very similar to what I was proposing.
