### ISSUE TITLE
Associating the gnu/msvc toolchains with OS's prevents using gnu on Windows

### ISSUE THREAD

**Issue by Zvax** [tensorflow/rust#274]
When compiling on Windows while using a gnu toolchain, the tensorflow-sys build file will try to download a file for Windows but with Unix compression. It happens here, when choosing the file extension:

https://github.com/tensorflow/rust/blob/c1a1f6bb0cea568ac301d7c58acfab797df18d63/tensorflow-sys/build.rs#L160-L163

These line assume that msvc will be Windows, and gnu Unix, however having a gnu toolchain activated on a Windows machine causes the build script to download the file `https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-windows-x86_64-1.15.0.tar.gz` (notice the "windows" associated with ".tar.gz") which does not exist because the Windows files are zip files.

When looking at the actual files available from [tensorflow](https://www.tensorflow.org/install/lang_c) it seems that the distinction is Windows / unix rather than msvc / gnu.

I have solved this locally by patching the extension lines as follows:

```
let ext = match os {
    "windows" => ".zip",
    _ => ".tar.gz",
};
```

and replacing all `target_env = "msvc"` checks with `target_os = "windows"` (the not conditions apply correctly to that new boolean).

Am I missing something that would make this break everything on other machines? Otherwise I believe that could be an improvement to the build script, as after this I can compile with both msvc and gnu, whereas before gnu will fail.

**Comment by adamcrume** [comment]
This looks like a straightforward improvement.  If you can submit a pull request, I'd be happy to accept it.

**Comment by adamcrume** [comment]
Can someone on Windows verify that https://github.com/tensorflow/rust/pull/277 fixes the issue?

**Comment by flaghacker** [comment]
I can confirm that this fixes the issue for me.

**Comment by adamcrume** [comment]
I added a new commit.  Can you try again?

**Comment by flaghacker** [comment]
That's [this commit](https://github.com/adamcrume/tensorflow-rust/commit/896bbb287dd0ced05c2f081f7b44fa408583b773), right?

I still get the same error unfortunately.

**Comment by adamcrume** [comment]
Yes, that commit.

I think I'll need help from someone developing on Windows.  I don't currently have a Windows environment to test in.

**Comment by ggopcceop** [comment]
I don't think using the `env::consts::OS` is a good idea in build.rs, because it will not work for a cross compile scenario. And maybe it is the case for @flaghacker under mingw32.

According to [cargo doc](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts), the `CARGO_CFG_TARGET_OS` should be used instead. 

And using the `CARGO_CFG_TARGET_ARCH` relpace the `env::consts::ARCH` at
https://github.com/tensorflow/rust/blob/896bbb287dd0ced05c2f081f7b44fa408583b773/tensorflow-sys/build.rs#L68

I would be happy to update the PR, or a new PR is preferred.

**Comment by adamcrume** [comment]
Good point.  I switched to using the Cargo environment variables.  It'll take more to support cross-compilation when building TensorFlow from source, but this should work for using prebuilt TensorFlow binaries.

If you can fix the Windows build, I'd be happy with either the existing PR being updated or a new one being created.

**Comment by ggopcceop** [comment]
i tried #277 on target `x86_64-pc-windows-gnu` on Ubunut. it complied without problems.

**Comment by flaghacker** [comment]
It compile fine now, thanks everyone!
