### ISSUE TITLE
0.16 is still broken on crates.io

### ISSUE THREAD

**Issue by photex** [tensorflow/rust#275]
Howdy! 

I noticed that the issue was already addressed in Git, but the latest version on crates.io is still broken. Would it be possible to publish a 0.16.x that includes that fix to the build script?

**Comment by adamcrume** [comment]
Can you  clarify what's still broken?

**Comment by photex** [comment]
Oh sorry, I thought it was known since master already has the fix for it.
The build script in tensorflow-sys is missing a use statement. If you try to build from crates it'll fail.

**Comment by adamcrume** [comment]
That's an issue with the Windows build, right?  The Windows build has some other issues, too, which I'm trying (unsuccessfully, so far) to fix in https://github.com/tensorflow/rust/pull/277.  If you have any Windows expertise, I'd really appreciate help in getting https://github.com/tensorflow/rust/issues/274 fixed (which is what that PR is about).

Once we get that working, then I can release 0.16.1.

**Comment by adamcrume** [comment]
I published version 0.16.1, which should fix this.
