### ISSUE TITLE
Will 1.15 still work with the version with 2.3 support?

### ISSUE THREAD

**Issue by xd009642** [tensorflow/rust#281]
Quick question, with the TF 2.3 PR merged, when this is released will it still be possible to work this with 1.15? Or will I have to upgrade my tensorflow version in my projects?

**Comment by adamcrume** [comment]
It should continue to work with 1.15, as long as you stick to features available in 1.15.  I haven't manually verified this, though.

By the way, the [relevant pull request](https://github.com/tensorflow/rust/pull/280) or [mailing list](https://groups.google.com/a/tensorflow.org/g/rust?pli=1) are good places to ask questions.
