### ISSUE TITLE
Link to library at runtime?

### ISSUE THREAD

**Issue by abrown** [tensorflow/rust#297]
Is there any interest to add a way to do runtime linking (e.g., using `libloading`) to installed TensorFlow shared libraries?

**Comment by dskkato** [comment]
Please check the following sub-crate/features.

https://github.com/tensorflow/rust/tree/master/tensorflow-sys-runtime

**Comment by abrown** [comment]
Yes, I think #382 closes this issue. I think we need a version bump and re-publish to see those latest changes in crates.io? @adamcrume, could you publish a new version?
