### ISSUE TITLE
Expose shape and data type info in TensorInfo

### ISSUE THREAD

**Issue by krlohnes** [tensorflow/rust#298]
It would be nice to be able to get the [shape and data type from the TensorInfo struct](https://github.com/tensorflow/rust/blob/e51522804cb329dd46065a526d892ece66c8dc4d/src/saved_model.rs#L111) so you can load a model and get that information.

**Comment by adamcrume** [comment]
Oh, you mean add accessors/getters for shape and data?  That would be a great beginner task, if anyone wants to take it.
