### ISSUE TITLE
Support graph generation

### ISSUE THREAD

**Issue by adamcrume** [tensorflow/rust#3]
The library should be able to generate computation graphs itself, rather than relying on Tensorflow's Python library.  We need a way to generate version 3 protobufs, though.  The obvious solution, https://github.com/stepancheg/rust-protobuf, does not support proto3.

**Comment by jeanm** [comment]
It seems that some progress has been made towards v3 support: <https://github.com/stepancheg/rust-protobuf/issues/76>

**Comment by adamcrume** [comment]
The new C API has functions for creating graph nodes without using protobufs.  I'm adding support for this on the tf-v0.10.0rc0 branch and will merge to master once it's reasonably feature complete (at least for basic things) and once #18 is resolved.

**Comment by xpe** [comment]
@adamcrume I'm interested in seeing how this is coming along (and helping out if useful).

**Comment by adamcrume** [comment]
The basics are now on the master branch and in version 0.1.0.  Graphs can be built using Rust expressions with the unfinished `expr` module, or by manipulating a `Graph` directly.  If you have suggestions for smoothing out the rough edges of the `expr` module, that'd be helpful.

**Comment by iduartgomez** [comment]
As part of a project, I've written (or rather finishing up) an abstraction layer over the current API to write graphs with similar ergonomics and functionality of the Python/C++ APIs (kind of a mix between both of them).

There is a bit of overlap with the 'expr' module, but it does things in a different way (plus adds a bunch load of functionality over it). Amongst other things it manages scopes, handles creations of variables and constants, and allows manipulation of tensors and ops in a similar way you would do in Python (with some differences and ofc it's not as extensive as the Python API, but the base is there, only implementing things I need so far but is relatively easy extend).

As an example, you can do something like this:
```Rust
    #[test]
    fn test_while_loop() {
        let mut context = ContextScope::new();
        let x = context.constant("", &[0_i32], &[]).unwrap();

        let pred = Box::new(
            move |mut scope: &mut ContextScope, loop_vars: &[Tensor]| {
                let y = scope.constant("", &[10_i32], &[]).unwrap();
                let x = loop_vars[0];
                less(&mut scope, x, y, "")
            },
        );

        let body = Box::new(
            move |mut scope: &mut TFContextScope,
                  loop_vars: &[Tensor]|
                  -> Result<Vec<Tensor>, ::Error> {
                let y = scope.constant("", &[1_i32], &[]).unwrap();
                let x = loop_vars[0];
                Ok(vec![add(scope, x, y, "")?])
            },
        );

        while_loop(&mut context, pred, body, &[x.into()], "").unwrap();
    }
```

this replicates the `tf.while_loop` function in Python.

There would be interesting in integrating something like this in the library (working out the details, refactoring stuff as necessary etc.)? I can always keep it as separate crate or as a fork, but thought there may be interest in this.

**Comment by sanmai-NL** [comment]
Very interesting to me.

**Comment by bklooste** [comment]
iduartgomez do you have your work somewhere ?

**Comment by iduartgomez** [comment]
@bklooste I haven't been able to work on this for the last month (along the other pull request I've pending), but I'm setting it up during this week.

will update here when it's ready

**Comment by iduartgomez** [comment]
@sanmai-NL @bklooste or anyone interested, I have finally added some documentation and examples to the library and is at least ready for testing, it also includes a lot of tests (which have to be moved to doc tests). A 0.0.1 release in crates.io will be done soon probably. Check it at https://github.com/iduartgomez/tf-rs

It still is incomplete (target for a 0.1.0 release would be parity with the C++ API), but adding new operations is relatively trivial (will be working on that gradually and adding more contributing guides). For any interests on this open issues in the library or contact me please,

Will leave this conversation for its original porpoise now.

**Comment by sanmai-NL** [comment]
@iduartgomez: that is great. My goal is to standardize on Rust even for training models. Will contact you soon, keep it up.

**Comment by adamcrume** [comment]
This has technically been possible for two and a half years now, so I'm closing this issue.  There's work to be done on making graph generation easier, but that'll be separate issues.
