### ISSUE TITLE
Migrating from Travis CI to GitHub Actions?

### ISSUE THREAD

**Issue by damienstanton** [tensorflow/rust#301]
Since travis-ci.org is shutting down, it probably makes sense to move this open project to another CI platform. GitHub actions seems like a low-friction environment.

Is this something the team would be interested in? If so, I would be willing to lead the effort to get a CI pipeline working again.

**Comment by adamcrume** [comment]
Sorry for the delay!  Yes, this would be very helpful.

**Comment by damienstanton** [comment]
Great! I have forked and gotten started on this. It should be relatively straightforward.

**Comment by damienstanton** [comment]
Just a quick update: Got delayed with other responsibilities but I am hoping to jump into this and get a PR up in the coming week or so.
