### ISSUE TITLE
Upgrade to TensorFlow 0.11

### ISSUE THREAD

**Issue by adamcrume** [tensorflow/rust#31]
Once TF 0.11 is released, we should upgrade tensorflow-sys and update the FFI bindings.

**Comment by delaneyj** [comment]
[Tensorflow 0.12 is now out and has support for windows!](https://developers.googleblog.com/2016/11/tensorflow-0-12-adds-support-for-windows.html).  Does this help in not having to build from source on windows?

**Comment by daschl** [comment]
@delaneyj afaik only 0.11 has been released , 0.12 is in rc0 right now, right?

**Comment by delaneyj** [comment]
`pip install tensorflow-gpu` works properly on Windows now, seems worthwhile to jump straight to 0.12 no?

**Comment by daschl** [comment]
I'd be good with it but its @adamcrume's call and I don't know how much C API is going to change

**Comment by adamcrume** [comment]
Fixed by https://github.com/tensorflow/rust/pull/43.  We jumped straight to TensorFlow 0.12.

**Comment by daschl** [comment]
Awesome 👏 thanks!!
