### ISSUE TITLE
expressions example

### ISSUE THREAD

**Issue by ChrisMacNaughton** [tensorflow/rust#32]
The expressions example (`examples/expressions.rs`) won't compile which also breaks `cargo test`

**Comment by adamcrume** [comment]
Are you passing the `--features tensorflow_unstable` flag?  (That API is unstable, so it's guarded behind a flag for the moment.)  If that doesn't fix it, please copy and paste the entire error message here, as well as the output of `rustc --version`.

**Comment by ChrisMacNaughton** [comment]
It works!
