### ISSUE TITLE
Pls upgrade dependant crate `pkg-config` to latest 0.3.24 to avoid its env vars ignoring bug

### ISSUE THREAD

**Issue by lnshi** [tensorflow/rust#349]
As showed in this [PR](https://github.com/rust-lang/pkg-config-rs/pull/105) the crate [pkg-config](https://github.com/tensorflow/rust/blob/master/tensorflow-sys/Cargo.toml#L27) ignores the env vars, pls help to upgrade it to the latest fixed release `0.3.24`.

Tested at my local, after upgrade, i am able to use my self-compiled TensorFlow other than that [build.rs](https://github.com/tensorflow/rust/blob/master/tensorflow-sys/build.rs#L54) always fail to get the external pkg-config libs.

**Comment by dskkato** [comment]
Could you open a PR to fix this? In addition to that, It may be appreciated if you could provide how to check whethere it is fixed. Is it just to build the tensorflow outside the crate?

**Comment by dskkato** [comment]
The current version is `0.3.25`, so this problem may have been resolved.

https://github.com/tensorflow/rust/blob/b40f8a7c23d6750ce6040e8cdd00a552d25aacda/tensorflow-sys/Cargo.toml#L31
