### ISSUE TITLE
Documentation generation for *Inst ops

### ISSUE THREAD

**Issue by Corallus-Caninus** [tensorflow/rust#365]
The *Inst ops need documentation generated for the user. This includes checking to ensure docstrings are formatted properly then updating doc gen and pull requesting.

I would like to be assigned this.

**Comment by adamcrume** [comment]
Docstrings are generated for the *Inst ops, and they're included when running `cargo doc`.  Is something else missing?

**Comment by Corallus-Caninus** [comment]
We may need to run docgen again since my last PR.
