### ISSUE TITLE
Installation help? 

### ISSUE THREAD

**Issue by rschulman** [tensorflow/rust#37]
This is perhaps one of those questions where I'm going to smack my for head at the answer, but..
I've built tensorflow/rust on my Linux computer and I now have a .rlib file, along with, presumably, the tensorflow .so file, but that's where the installation instructions stop. What are the next steps for getting those files where they need to be to use them in my own project? How do I tell cargo to use it? 

Thanks so much!

**Comment by adamcrume** [comment]
You don't need to build tensorflow/rust on its own.  Just add `tensorflow = "0.1"` to the `[dependencies]` section of your project's Cargo.toml.

**Comment by rschulman** [comment]
Yep, that's headsmack worthy. If you don't mind, I might do a PR on readme.md to add a section up front on just using the crate. Right now it does kind of read as if you need to build it all yourself in order to use it. 

Am I correct that even just to use the crate from Cargo.toml you still have to have bazel installed?

**Comment by adamcrume** [comment]
You still need Bazel because it still builds TensorFlow from source, even though it's automated.  I've tried to write it so that it doesn't build TensorFlow if libtensorflow.so is already installed, but that feature seems to be a bit flaky.

**Comment by rschulman** [comment]
Closed because fixed by https://github.com/tensorflow/rust/issues/44.
