### ISSUE TITLE
Session `extend_graph` or similar missing from new api

### ISSUE THREAD

**Issue by DrRibosome** [tensorflow/rust#38]
The deprecated `Session` struct has a method for loading a graph from a protobuf description (`extend_graph`), which appears to be missing under the new api. Is there another recommended way to load protobuf graphs?

**Comment by adamcrume** [comment]
It's added in the C API for TensorFlow 0.11.0, which the Rust bindings will support in the next release.

**Comment by adamcrume** [comment]
As of https://github.com/tensorflow/rust/pull/43, there is now `Graph::import_graph_def()`.
