### ISSUE TITLE
Please publish a new release on crates.io

### ISSUE THREAD

**Issue by brianjjones** [tensorflow/rust#392]
Several changes and fixes have been implemented in the previous months, can we get a new release please? Some projects don't allow for pulling from github and require a published crate.

Thanks in advance.

**Comment by dskkato** [comment]
@adamcrume ping.

Do you have any plan for the next release?

**Comment by dskkato** [comment]
@brianjjones 

v0.20.0 was released yesterday.

https://crates.io/crates/tensorflow/0.20.0

**Comment by adamcrume** [comment]
Yep, sorry for the delay!
