### ISSUE TITLE
How can I use tf.signal.stft in rust binding?

### ISSUE THREAD

**Issue by namse** [tensorflow/rust#421]
I'm trying to follow this tutorial in rust https://www.tensorflow.org/tutorials/audio/simple_audio but I couldn't find tf.signal.stft in rust version.

**Comment by adamcrume** [comment]
Unfortunately, a lot of TensorFlow functionality is written directly in Python, not the underlying C++, which means that we can't use it from Rust.  It looks like `tf.signal.stft` is one of these.  Rust does expose the underlying FFT ops, so you could build that yourself by FFT-ing slices of your data.
