### ISSUE TITLE
Use required-features in Cargo.toml

### ISSUE THREAD

**Issue by adamcrume** [tensorflow/rust#64]
The `expressions` example only makes sense with the `tensorflow_unstable` feature enabled.  It currently compiles to a no-op if the feature isn't present, but even better would be to use the new `required-features` field.

http://doc.crates.io/manifest.html#the-required-features-field-optional

**Comment by adamcrume** [comment]
Note: The `required-features` field doesn't appear to be present in cargo 0.16.0-nightly, which is used in the current stable release of rust.

**Comment by sanmai-NL** [comment]
I've tried to check whether the field is supported with current stable Rust, but I haven't managed to find a procedure to do so. Best way is that you list the steps you took so others can carry those out again later (and list also the exact versions of things you check against, e.g. stable Rust version).

**Comment by adamcrume** [comment]
I tried adding
```
[[example]]
name = "expressions"
required-features = ["tensorflow_unstable"]
```
to Cargo.toml.

Running `cargo run --example expressions` against nightly (rustc 1.19.0-nightly (75b056812 2017-05-15) and cargo 0.20.0-nightly (13d92c64d 2017-05-12)) correctly prints
```
error: target `expressions` requires the features: `tensorflow_unstable`
Consider enabling them by passing e.g. `--features="tensorflow_unstable"`
```
but running against stable (rustc 1.16.0 (30cf806ef 2017-03-10) and cargo-0.17.0-nightly (f9e5481 2017-03-03)) prints
```
warning: unused manifest key: example.required-features
```

I'm using multirust, and for some reason it's using 1.16 for the stable channel, when it should be using 1.17.

**Comment by Enet4** [comment]
> I'm using multirust, and for some reason it's using 1.16 for the stable channel, when it should be using 1.17.

Don't you mean Rustup? Multirust has been obsolete for a while. According to the announcement of version 1.17,  `required-features` is already available in stable, so you might just need to update your toolchains.

**Comment by adamcrume** [comment]
No, I meant multirust.  I didn't realize it had been deprecated.  I guess I have to swtich. :/  I have some commits in the works, and this will be fixed in one of them.
