### ISSUE TITLE
Could not find `expr` in `tensorflow`

### ISSUE THREAD

**Issue by zaabjuda** [tensorflow/rust#85]
Hi!
I'm trying to run an example from examples/expressions.rs. At start I get the following error

> error[E0432]: unresolved import `tensorflow::expr::Compiler`
 --> src/main.rs:8:24
  |
8 | use tensorflow::expr::{Compiler, Placeholder};
  |                        ^^^^^^^^ Could not find `expr` in `tensorflow`

> error[E0432]: unresolved import `tensorflow::expr::Placeholder`
 --> src/main.rs:8:34
  |
8 | use tensorflow::expr::{Compiler, Placeholder};
  |                                  ^^^^^^^^^^^ Could not find `expr` in `tensorflow`

My Cargo.toml 

```
[package]  
name = "tflow_test"
version = "0.1.0"
authors = ["Zhiltsov Dmitriy <dzhiltsov@me.com>"]
[dependencies]
# tensorflow = { git = "https://github.com/tensorflow/rust" }
tensorflow = {version = "0.4.0"}
random = "*"
[features]
tensorflow_unstable = []
```
I see that the module expr is declared as [public] (https://github.com/tensorflow/rust/blob/master/src/lib.rs#L166)
Can you help with this problem?

**Comment by Enet4** [comment]
The features field should actually be on the `tensorflow` dependency. See if this works:

    tensorflow = { version = "0.4.0", features = ["tensorflow_unstable"] }

**Comment by zaabjuda** [comment]
@Enet4 Thx!
